config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#homepage'

  resource :account, only: [:new, :create, :destroy]
  resources :recipients, only: [:index, :new, :create] do
    resources :payments, only: [:index, :new, :create]
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  validates :user_id, :api_key, :username, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  validates :currency, :payment_id, :amount, :recipient_id, presence: true
  belongs_to :recipient
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  validates :name, :recipient_id, :user_id, presence: true
  belongs_to :user
  has_many :payments
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :account
  has_many :recipients
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @user = current_user.account || current_user.build_account
  end

  def create
    @user = current_user.build_account(account_params)
    if @user.save
      redirect_to root_path
    else
      flash.now[:alert] = "ERROR: #{@user.errors.full_messages}"
      render :new
    end
  end

  def destroy
    current_user.account.destroy
    redirect_to root_path
  end


  private

  def account_params
    params.require(:account).permit(:username, :api_key)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def auth
    current_user.account ? set_token : redirect_to(main_app.new_account_path)
  end

  private

  def set_token
    response = RestClient.post url, set_values, set_headers
    @token = JSON.parse(response)['token']
  end

  def set_headers
    { 'Content-Type' => 'application/json' }
  end

  def set_values
    username = current_user.account.username
    api_key = current_user.account.api_key
    "{\"username\": \"#{username}\", \"apikey\": \"#{api_key}\"}"
  end

  def url
    "#{CurrencyCloudTest::Application.config.coolpay_base_url}/login"
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :auth, :recipient

  def index
    @payments = recipient_payments.sort_by do |line|
      line["created_at"]
    end.reverse
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = recipient.payments.new create_params
    if @payment.save
      redirect_to recipient_payments_path(recipient.id)
    else
      flash.now[:alert] = "ERROR: #{@payment.errors.full_messages}"
      render :new
    end
  end

  private

  def recipient
    @recipient ||= Recipient.find params[:recipient_id]
  end

  def payment_params
    params.require(:payment).permit(:currency, :amount)
  end

  def set_payment_header
    {
      'Content-Type' => 'application/json',
      'Authorization' => "Bearer #{@token}"
    }
  end

  def set_payment_values
    {
      payment: {
        amount: payment_params[:amount],
        currency: payment_params[:currency],
        recipient_id: recipient.recipient_id
      }
    }.to_json
  end

  def payment_url
    "#{CurrencyCloudTest::Application.config.coolpay_base_url}/payments"
  end

  def create_params
    new_params = payment_params.merge(payment_id: payment_response[:id])
    new_params.merge(payment_response.slice!(:id))
  end

  def recipient_payments
    response = RestClient.get payment_url, set_payment_header
    json_response = JSON.parse(response)['payments'] || []
    process_payment(json_response)
  end

  def process_payment(json_respone)
    json_respone.map do |response_line|
      database_payment = check_payment_response(response_line['id'])
      if database_payment
        response_line.merge('created_at' => database_payment.created_at)
      end
    end.compact
  end

  def check_payment_response(id)
    recipient.payments.find_by(payment_id: id)
  end

  def payment_response
    response = JSON.parse(request_payment)['payment']
    response.slice!('recipient_id', 'status').symbolize_keys
  end

  def request_payment
    RestClient.post payment_url, set_payment_values, set_payment_header
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_action :auth

  def index
    @recipients = Recipient.all
  end

  def new
    @recipient = Recipient.new
  end

  def create
    create_params = recipient_params.merge(recipient_id: recipient_id)
    @recipient = current_user.recipients.new create_params
    if @recipient.save
      redirect_to recipients_path
    else
      flash.now[:alert] = "ERROR: #{@recipient.errors.full_messages}"
      render :new
    end
  end

  private

  def recipient_params
    params.require(:recipient).permit(:name)
  end

  def recipient_id
    JSON.parse(request_recipient)['recipient']['id']
  end

  def request_recipient
    RestClient.post recipient_url, set_recipient_values, set_recipient_header
  end

  def set_recipient_header
    {
      'Content-Type' => 'application/json',
      'Authorization' => "Bearer #{@token}"
    }
  end

  def set_recipient_values
    '{"recipient": {"name": "' + recipient_params[:name] + '"} }'
  end

  def recipient_url
    "#{CurrencyCloudTest::Application.config.coolpay_base_url}/recipients"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/new.html.slim
= form_for @user, url: account_path do |f|
  | Username:
  = f.text_field :username, placeholder: "Username", required: true
  br
  | Api Key:
  = f.text_field :api_key, placeholder: "API_Key", required: true
  br
  = f.submit "add"

app/views/layouts/application.html.slim
doctype html
html
  head
    title Fakebook Test App
      = csrf_meta_tags
      = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
      = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - if notice
      h3.alert.alert-success = notice
    - elsif alert
      h3.alert.alert-danger = alert
    h3 = link_to 'Home Page', root_path
    br
    = yield

app/views/payments/index.html.slim
| Payments:
br
br
- if @payments.any?
  table
    thead
     tr
      th Date money was sent
      th Currency
      th Amount
      th Status

    tbody
    - @payments.each do |cp|
      tr
        td = cp['created_at'].strftime("%a %d %b  %H:%M:%S")
        td = cp['currency']
        td = cp['amount']
        td = cp['status']
  br
- else
  br
  | --No payments--
  br
br
= link_to 'Create Payment', new_recipient_payment_path(@recipient)
br
= link_to 'All Recipients', recipients_path

app/views/payments/new.html.slim
p = "Send Money to #{@recipient.name}"
= form_for @payment, url: recipient_payments_path, method: :post do |f|
  | Currency:
  = f.text_field :currency, placeholder: "USD, EUR or GBP,", required: true
  br
  | Amount:
  = f.text_field :amount, placeholder: "500.50, 10.25, etc", required: true
  br
  = f.submit "add"

app/views/recipients/index.html.slim
| Recipients:
br
br
- if @recipients.any?
  - @recipients.each do |recipient|
    = recipient.name
    br
    = link_to 'All Payments', recipient_payments_path(recipient)
    | &nbsp;&nbsp;
    = link_to 'Send Money', new_recipient_payment_path(recipient)
    br
    br
- else
  br
  | --No recipients--
  br
br
= link_to 'Add Recipient', new_recipient_path

app/views/recipients/new.html.slim
= form_for @recipient do |f|
  | Name:
  = f.text_field :name, placeholder: "Ken Bone", required: true
  br
  = f.submit "Add"

app/views/static_pages/homepage.html.slim
= link_to 'All Recipients', recipients_path
br
= link_to 'add recipient', new_recipient_path
br
br
| Account
br
- if current_user.account
  = button_to 'remove', '/account', method: :delete
- else
  = link_to 'add', new_account_path